"""Alteracoes na tabela Mensagens

Revision ID: 2f9a632e2261
Revises: 0abc847012c7
Create Date: 2024-09-06 01:09:16.003715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f9a632e2261'
down_revision = '0abc847012c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Mensagens', schema=None) as batch_op:
        batch_op.drop_constraint('Mensagens_ibfk_2', type_='foreignkey')
        batch_op.drop_column('id_destinatario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Mensagens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_destinatario', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('Mensagens_ibfk_2', 'Usuarios', ['id_destinatario'], ['id_usuario'])

    # ### end Alembic commands ###
